/+
 +  Protocol copyright:
 +  Copyright © 2008-2011 Kristian Høgsberg
 +  Copyright © 2010-2011 Intel Corporation
 +  Copyright © 2012-2013 Collabora, Ltd.
 +
 +  Permission is hereby granted, free of charge, to any person
 +  obtaining a copy of this software and associated documentation files
 +  (the "Software"), to deal in the Software without restriction,
 +  including without limitation the rights to use, copy, modify, merge,
 +  publish, distribute, sublicense, and/or sell copies of the Software,
 +  and to permit persons to whom the Software is furnished to do so,
 +  subject to the following conditions:
 +
 +  The above copyright notice and this permission notice (including the
 +  next paragraph) shall be included in all copies or substantial
 +  portions of the Software.
 +
 +  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 +  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 +  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 +  NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 +  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 +  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 +  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 +  SOFTWARE.
 +/
/+
 +  D bindings copyright:
 +  Copyright © 2015 Rémi Thebault
 +/
/+
 +      File generated by wayland-scanner-d:
 +  ../wayland-scanner-d/wayland-scanner-d -m wayland.client.priv.ifaces --client --ifaces --ifaces_priv -o ./src/wayland/client/priv/ifaces.d
 +      Do not edit!
 +/
module wayland.client.priv.ifaces;

import wayland.client.util;
import wayland.client.opaque_types;

extern (C) {

    version (Dynamic) {}
    else {
        extern __gshared wl_interface wl_display_interface;
        extern __gshared wl_interface wl_registry_interface;
        extern __gshared wl_interface wl_callback_interface;
        extern __gshared wl_interface wl_compositor_interface;
        extern __gshared wl_interface wl_shm_pool_interface;
        extern __gshared wl_interface wl_shm_interface;
        extern __gshared wl_interface wl_buffer_interface;
        extern __gshared wl_interface wl_data_offer_interface;
        extern __gshared wl_interface wl_data_source_interface;
        extern __gshared wl_interface wl_data_device_interface;
        extern __gshared wl_interface wl_data_device_manager_interface;
        extern __gshared wl_interface wl_shell_interface;
        extern __gshared wl_interface wl_shell_surface_interface;
        extern __gshared wl_interface wl_surface_interface;
        extern __gshared wl_interface wl_seat_interface;
        extern __gshared wl_interface wl_pointer_interface;
        extern __gshared wl_interface wl_keyboard_interface;
        extern __gshared wl_interface wl_touch_interface;
        extern __gshared wl_interface wl_output_interface;
        extern __gshared wl_interface wl_region_interface;
        extern __gshared wl_interface wl_subcompositor_interface;
        extern __gshared wl_interface wl_subsurface_interface;
    }

} // extern (C)

